Update paru-hyprland
Signed-off-by: Ja.KooLit <85185940+JaKooLit@users.noreply.github.com>

diff --git a/paru-hyprland b/paru-hyprland
--- a/paru-hyprland
+++ b/paru-hyprland
@@ -1,8 +1,9 @@
 #!/bin/bash
-# The following will be installed to run Hyprland on Asus G15 with RTX GPU
+# The following will be installed to run Hyprland on your system
 # 
 # NOTE! IF YOU ADD OR REMOVE PACKAGES, make sure proper spelling as per AUR and official Arch Repo and that are present.
 # Adding packages not in AUR or official Arch Repo, script will fail.
+#
 #
 # Below is a list of the packages that would be installed
 # hyprland- This is the Hyprland compositor
@@ -36,13 +37,48 @@
 # qt5ct: for visual settings for qt-apps
 # mousepad: simple text editor
 
-
 # Define color variables
 GREEN="$(tput setaf 2)[OK]$(tput sgr0)"
 RED="$(tput setaf 1)[ERROR]$(tput sgr0)"
 YELLOW="$(tput setaf 3)[NOTE]$(tput sgr0)"
 CAT="$(tput setaf 6)[ACTION]$(tput sgr0)"
 
+# Set the script to exit on error
+set -e
+
+printf "$(tput setaf 2) Welcome to the Arch Linux PARU Hyprland installer!\n $(tput sgr0)"
+
+sleep 3
+
+printf "$YELLOW PLEASE BACKUP YOUR FILES BEFORE PROCEEDING!
+This script will overwrite some of your configs and files!"
+
+sleep 2
+
+printf "\n
+$YELLOW  Some commands requires you to enter your password inorder to execute
+If you are worried about entering your password, you can cancel the script now with CTRL Q or CTRL C and review contents of this script. \n"
+
+sleep 2
+# Check if paru is installed
+ISparu=/sbin/paru
+if [ -f "$ISparu" ]; then
+    printf "\n%s - paru was located, moving on.\n" "$GREEN"
+else 
+    printf "\n%s - paru was NOT located\n" "$YELLOW"
+    read -n1 -rep "${CAT} Would you like to install paru (y,n)" INSTparu
+    if [[ $INSTparu == "Y" || $INSTparu == "y" ]]; then
+        git clone https://aur.archlinux.org/paru-bin.git
+        cd paru-bin
+        makepkg -si --noconfirm 
+        cd ..
+    else
+        printf "%s - paru is required for this script, now exiting\n" "$RED"
+        exit
+    fi
+fi
+
+# Prompt user to install packages
 # Function to check if a command executed successfully
 function check_command_status {
     if [ $? -ne 0 ]; then
@@ -50,42 +86,15 @@ function check_command_status {
         exit 1
     fi
 }
-
 # Function to print error messages
 print_error() {
-    printf "%sError: %s%s\n" "$RED" "$1" "$NC" >&2
+    printf " %s%s\n" "$RED" "$1" "$NC" >&2
 }
 
 # Function to print success messages
 print_success() {
     printf "%s%s%s\n" "$GREEN" "$1" "$NC"
 }
-
-# Set the script to exit on error
-set -e
-
-printf "Welcome to the Arch Linux Hyprland installer!\n"
-sleep 3
-
-# Check if paru is installed
-ISPARU=/sbin/paru
-if [ -f "$ISPARU" ]; then
-    printf "%s - paru was located, moving on.\n" "$GREEN"
-else 
-    printf "%s - paru was NOT located\n" "$YELLOW"
-    read -n1 -rep "${CAT} Would you like to install paru (y,n)" INSTPARU
-    if [[ $INSTPARU == "Y" || $INSTPARU == "y" ]]; then
-        git clone https://aur.archlinux.org/paru-bin.git
-        cd paru-bin
-        makepkg -si --noconfirm 
-        cd ..
-    else
-        printf "%s - Paru is required for this script, now exiting\n" "$RED"
-        exit
-    fi
-fi
-
-# Prompt user to install packages
 
 # Install necessary packages
 read -n1 -rep "${CAT} Would you like to install the packages? (y/n)" inst
@@ -103,31 +112,31 @@ if [[ $inst =~ ^[Yy]$ ]]; then
         fi
     else
         # Install non-Nvidia Hyprland
-        echo -e "${YELLOW} None Nvidia-Hyprland will be installed."
+        printf "${YELLOW} None Nvidia-Hyprland will be installed."
         if ! paru -S --noconfirm hyprland; then
-            print_error "Failed to install Hyprland."
+            print_error " Failed to install Hyprland."
             exit 1
         fi
     fi
 
-    echo -e "${YELLOW} Installing additional packages. Please wait..."
+    printf "${YELLOW} Installing additional packages. Please wait..."
     sleep 1
 
     # Install packages
     font_pkgs="otf-font-awesome ttf-jetbrains-mono-nerd otf-font-awesome-4 ttf-fantasque-sans-mono"
     theme_pkgs="dracula-gtk-theme bibata-cursor-theme-bin"
-    app_pkgs="foot swaybg swaylock-effects wofi wlogout mako thunar gvfs thunar-volman tumbler ffmpegthumbs qt5ct wl-clipboard polkit-gnome python-requests grim slurp pamixer brightnessctl viewnior pavucontrol mpv network-manager-applet mousepad mpv bluez bluez-utils blueman nwg-look-bin"
+    app_pkgs="foot swaybg swaylock-effects wofi wlogout mako thunar btop jq gvfs thunar-volman tumbler ffmpegthumbs qt5ct wl-clipboard polkit-gnome python-requests grim slurp pamixer brightnessctl viewnior pavucontrol mpv network-manager-applet mousepad mpv bluez bluez-utils blueman nwg-look-bin"
 
         
     if ! paru -S --noconfirm $hyprland_pkg waybar-hyprland-git xdg-desktop-portal-hyprland dracula-icons-git $font_pkgs $theme_pkgs $app_pkgs; then
-        print_error "Failed to install additional packages."
+        print_error " Failed to install additional packages."
         exit 1
     fi
 
     # Start the bluetooth service
-    echo -e "${YELLOW} Starting the Bluetooth service..."
+    printf "\n${YELLOW} Starting the Bluetooth service..."
     if ! sudo systemctl enable --now bluetooth.service; then
-        print_error "Failed to start the Bluetooth service."
+        print_error " Failed to start the Bluetooth service."
         exit 1
     fi
 
@@ -140,7 +149,7 @@ else
 fi
    
  # Clean out other portals
-echo -e "\nChecking if any other xdg-desktop-portals exist..."
+printf "\n${YELLOW} Checking if any other xdg-desktop-portals exist...\n"
 
 # Check if packages are installed and uninstall if present
 if pacman -Qs xdg-desktop-portal-gnome > /dev/null ; then
@@ -176,7 +185,7 @@ set -e # Exit immediately if a command exits with a non-zero status.
 
 read -n1 -rep "${CAT} Would you like to copy config and wallpaper files? (y,n)" CFG
 if [[ $CFG == "Y" || $CFG == "y" ]]; then
-    echo -e "Copying config files...\n"
+    printf " Copying config files...\n"
     mkdir -p ~/.config
     cp -r config/hypr ~/.config/ || { echo "Error: Failed to copy hypr config files."; exit 1; }
     cp -r config/foot ~/.config/ || { echo "Error: Failed to copy foot config files."; exit 1; }
@@ -204,49 +213,50 @@ if [[ $CFG == "Y" || $CFG == "y" ]]; then
     chmod +x ~/.config/hypr/scripts/volume
     chmod +x ~/.config/hypr/scripts/weather.sh
     chmod +x ~/.config/hypr/scripts/wofi-beats
+else
+   print_error " No Config files and wallpaper files copied"
 fi
 
 
 ### Install software for Asus ROG laptops ###
-read -n1 -rep "${CAT} OPTIONAL - ONLY for ROG Laptops) Would you like to install Asus ROG software support? (y/n)" ROG
+read -n1 -rep "${CAT} (OPTIONAL - ONLY for ROG Laptops) Would you like to install Asus ROG software support? (y/n)" ROG
 if [[ $ROG =~ ^[Yy]$ ]]; then
-    echo -e "\nInstalling ASUS ROG packages...\n"
+    printf " Installing ASUS ROG packages...\n"
     paru -S --noconfirm asusctl 
     paru -S --noconfirm supergfxctl 
     paru -S --noconfirm rog-control-center
     
-    echo -e "\nActivating ROG services...\n"
+    printf " Activating ROG services...\n"
     sudo systemctl daemon-reload && sudo systemctl enable --now supergfxd
     sleep 2
 else
-    echo -e "\nAsus ROG software support not installed."
+    printf "${YELLOW} Asus ROG software support not installed..\n"
 fi
 
 ### Disable wifi powersave mode ###
 read -n1 -rep "${CAT} Would you like to disable wifi powersave? (y,n)" WIFI
 if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
     LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
-    echo -e "$YELLOW The following has been added to $LOC.\n"
-    echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
-    echo -e "\n"
-    echo -e "$YELLOW Restarting NetworkManager service...\n"
+    printf "${YELLOW} The following has been added to $LOC.\n"
+    printf "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
+    printf "\n"
+    printf "${YELLOW} Restarting NetworkManager service...\n"
     sudo systemctl restart NetworkManager
     sleep 3
 fi
 ### Script is done ###
-echo -e "Installation Completed.\n"
-echo -e "You can start Hyprland by typing Hyprland (note the capital H!).\n"
-echo -e "${YELLOW} No Login Manager installed. You can start Hyprland by typing Hyprland (note the capital H!).\n"
-echo -e "${YELLOW} It is highly recommended to reboot your computer first.\n"
-read -n1 -rep "Would you like to start Hyprland now? (y,n)" HYP
+printf "\n${GREEN} Installation Completed.\n"
+printf "\n${YELLOW} You can start Hyprland by typing Hyprland (note the capital H!).\n"
+printf "\n${YELLOW} No Login Manager installed. You can start Hyprland by typing Hyprland (note the capital H!).\n"
+printf "\n${YELLOW} It is highly recommended to reboot your computer first.\n"
+read -n1 -rep "${CAT} Would you like to start Hyprland now? (y,n)" HYP
 if [[ $HYP == "Y" || $HYP == "y" ]]; then
     if command -v Hyprland >/dev/null; then
         exec Hyprland
     else
-        echo -e "Hyprland not found. Please make sure it is installed and try again.\n"
+         print_error " Hyprland not found. Please make sure it is installed and try again.\n"
         exit 1
     fi
 else
     exit
 fi
-
