Update yay-hyprland
Signed-off-by: Ja.KooLit <ejhay.games@gmail.com>

diff --git a/yay-hyprland b/yay-hyprland
--- a/yay-hyprland
+++ b/yay-hyprland
@@ -1,11 +1,10 @@
 #!/bin/bash
-# The following will be installed to run Hyprland on your system
-# 
 # NOTE! IF YOU ADD OR REMOVE PACKAGES, make sure proper spelling as per AUR and official Arch Repo and that are present.
-# Adding packages not in AUR or official Arch Repo, script will fail.
+# Adding packages not in AUR or official Arch Repo, this script will fail. 
 #
+# Enjoy!
 #
-# Below is a list of the packages that would be installed
+# Here are list of the packages that would be installed
 # hyprland- This is the Hyprland compositor
 # foot: This is the default terminal
 # waybar-hyprland: This is a fork of waybar with Hyprland workspace support
@@ -14,7 +13,7 @@
 # wofi: This is an application launcher menu
 # wlogout: This is a logout menu that allows for shutdown, reboot and sleep
 # mako: This is a graphical notification daemon
-# thunar with necessary plugins: This is a graphical file manager
+# thunar with necessary plugins: This is a graphical file manager. Note, not all plugins included. See readme notes
 # ttf-jetbrains-mono-nerd : some nerd fonts needed for proper icons in waybar
 # otf-font-awesome-4 and otf-font-awesome # necessary for symbols / weather
 # ttf-droid - suggested for international fonts to display properly
@@ -25,17 +24,17 @@
 # viewnior: for photo viewing
 # pamixer: This helps with audio settings such as volume
 # brightnessctl: used to control monitor bright level
-# bluez: the bluetooth service
-# bluez-utils: command line utilities to interact with bluetooth devices
-# blueman - Bluetooth manager
-# lxappearance: used to set GTK theme
-# dracula-gtk-theme: the Dracula theme, it fits the overall look and feel
-# dracula-icons-git" set of icons to go with the Dracula theme
-# bibata-cursor-theme-bin - cursor theme
-# xdg-desktop-portal-hyprland-git: xdg-desktop-portal backend for hyprland
-# mpv: for wofi-beats to work
+# nwg-look: used to set GTK theme
+# xdg-desktop-portal-hyprland: xdg-desktop-portal backend for hyprland
+# mpv: Video player and for wofi-beats to work
 # qt5ct: for visual settings for qt-apps
 # mousepad: simple text editor
+
+# OPTIONAL - packages to be installed. (you will be asked on the script)
+# Bluetooth packages (blueman, bluez, bluez-utils)
+# Dracula icons and themes
+# Bibata Cursor theme
+# Asusctl, Supergfxctl (ASUS ROG laptop stuffs)
 
 # Define color variables
 GREEN="$(tput setaf 2)[OK]$(tput sgr0)"
@@ -62,18 +61,19 @@ If you are worried about entering your password, you can cancel the script now w
 sleep 2
 # Check if yay is installed
 ISyay=/sbin/yay
+
 if [ -f "$ISyay" ]; then
     printf "\n%s - yay was located, moving on.\n" "$GREEN"
 else 
     printf "\n%s - yay was NOT located\n" "$YELLOW"
-    read -n1 -rep "${CAT} Would you like to install yay (y,n)" INSTyay
-    if [[ $INSTyay == "Y" || $INSTyay == "y" ]]; then
+    read -n1 -rep "${CAT} Would you like to install yay (y,n)" INSTALL-yay
+    if [[ $INSTALL-yay =~ ^[Yy]$ ]]; then
         git clone https://aur.archlinux.org/yay-bin.git
         cd yay-bin
         makepkg -si --noconfirm 
         cd ..
     else
-        printf "%s - yay is required for this script,......exiting\n" "$RED"
+        printf "%s - yay is required for this script, now exiting\n" "$RED"
         exit
     fi
 # update system before proceed
@@ -133,19 +133,12 @@ if [[ $inst =~ ^[Yy]$ ]]; then
     # Install packages
    hypr_pkgs="waybar-hyprland foot swaybg swaylock-effects wofi wlogout mako xdg-desktop-portal-hyprland  grim slurp wl-clipboard polkit-gnome"    
    font_pkgs="otf-font-awesome ttf-jetbrains-mono-nerd otf-font-awesome-4 ttf-fantasque-sans-mono"
-   app_pkgs="nwg-look-bin qt5ct thunar btop jq gvfs thunar-volman tumbler ffmpegthumbs  mousepad mpv bluez bluez-utils blueman "
+   app_pkgs="nwg-look-bin qt5ct thunar btop jq gvfs thunar-volman tumbler ffmpegthumbs  mousepad mpv"
    app_pkgs2="python-requests  pamixer brightnessctl viewnior pavucontrol playerctl mpv network-manager-applet cava"
 
        
     if ! yay -S --noconfirm $hypr_pkgs $font_pkgs $app_pkgs $app_pkgs2; then
         print_error " Failed to install additional packages.\n"
-        exit 1
-    fi
-
-    # Start the bluetooth service
-    printf "\n${YELLOW} Starting the Bluetooth service..."
-    if ! sudo systemctl enable --now bluetooth.service; then
-        print_error " Failed to start the Bluetooth service."
         exit 1
     fi
 
@@ -170,10 +163,9 @@ read -n1 -rep "${CAT} OPTIONAL - Would you like to install Dracula Icons and The
     else
         printf "${YELLOW} No additional themes installed.\n"
         fi
-    
-   
+ 
  # Clean out other portals
-printf "\n${YELLOW} Checking if any other xdg-desktop-portals exist...\n"
+printf "${YELLOW} Clearing any other xdg-desktop-portal implementations...\n"
 
 # Check if packages are installed and uninstall if present
 if pacman -Qs xdg-desktop-portal-gnome > /dev/null ; then
@@ -208,7 +200,7 @@ print_success " All other XDG-DESKTOP-PORTAL Implementation Cleared"
 set -e # Exit immediately if a command exits with a non-zero status.
 
 read -n1 -rep "${CAT} Would you like to copy config and wallpaper files? (y,n)" CFG
-if [[ $CFG == "Y" || $CFG == "y" ]]; then
+if [[ $CFG =~ ^[Yy]$ ]]; then
     printf " Copying config files...\n"
     mkdir -p ~/.config
     cp -r config/hypr ~/.config/ || { echo "Error: Failed to copy hypr config files."; exit 1; }
@@ -245,25 +237,39 @@ else
    print_error " No Config files and wallpaper files copied"
 fi
 
-
+# BLUETOOTH
+read -n1 -rep "${CAT} OPTIONAL - Would you like to install Bluetooth packages? (y/n)" BLUETOOTH
+if [[ $BLUETOOTH =~ ^[Yy]$ ]]; then
+    printf " Installing Bluetooth Packages...\n"
+ blue_pkgs="bluez bluez-utils blueman"
+    if ! yay -S --noconfirm $blue_pkgs; then
+       	print_error "Failed to install ROG packages"    
+    printf " Activating Bluetooth Services...\n"
+    sudo systemctl enable --now bluetooth.service
+    sleep 2
+    fi
+else
+    printf "${YELLOW} No bluetooth packages installed..\n"
+	fi
+ 
 ### Install software for Asus ROG laptops ###
 read -n1 -rep "${CAT} (OPTIONAL - ONLY for ROG Laptops) Would you like to install Asus ROG software support? (y/n)" ROG
 if [[ $ROG =~ ^[Yy]$ ]]; then
     printf " Installing ASUS ROG packages...\n"
-    yay -S --noconfirm asusctl 
-    yay -S --noconfirm supergfxctl 
-    yay -S --noconfirm rog-control-center
-    
+ ROG_pkgs="asusctl supergfxctl rog-control-center"
+    if ! yay -S --noconfirm $ROG_pkgs; then
+       	print_error "Failed to install ROG packages"    
     printf " Activating ROG services...\n"
     sudo systemctl daemon-reload && sudo systemctl enable --now supergfxd
     sleep 2
+    fi
 else
     printf "${YELLOW} Asus ROG software support not installed..\n"
 fi
 
 ### Disable wifi powersave mode ###
 read -n1 -rep "${CAT} Would you like to disable wifi powersave? (y,n)" WIFI
-if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
+if [[ $WIFI =~ ^[Yy]$ ]]; then
     LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
     printf "${YELLOW} The following has been added to $LOC.\n"
     printf "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
@@ -278,7 +284,7 @@ printf "\n${YELLOW} You can start Hyprland by typing Hyprland (note the capital 
 printf "\n${YELLOW} No Login Manager installed. You can start Hyprland by typing Hyprland (note the capital H!).\n"
 printf "\n${YELLOW} It is highly recommended to reboot your computer first.\n"
 read -n1 -rep "${CAT} Would you like to start Hyprland now? (y,n)" HYP
-if [[ $HYP == "Y" || $HYP == "y" ]]; then
+if [[ $HYP =~ ^[Yy]$ ]]; then
     if command -v Hyprland >/dev/null; then
         exec Hyprland
     else
